language: ruby
jdk:
- oraclejdk8
sudo: false
rvm:
- 2.3.1
before_install:
- openssl aes-256-cbc -K $encrypted_02ff0eb47d03_key -iv $encrypted_02ff0eb47d03_iv -in etc/secrets -out ../secrets.tar -d
- "(cd ../ && tar xvf secrets.tar)"
- chmod 600 ../release.asc
- gpg --import ../release.asc
install:
- rvm use 2.3.1
- gem install bundler
- bundle install
script: buildr clean package jacoco:report publish_if_tagged
after_success:
- bash <(curl -s https://codecov.io/bash)
git:
  depth: false
env:
  global:
  - secure: sSguVrR4oJxCW/Xy1THyHivsK27VhxtZsnNahiDUYyA8a8YLC2Ignam0F1mbTmki/aXHsPk7FnUKoIRTLZEyz6S4qUn/e92l25ujsK3R+2eEBg9okgyVImJBjC1dB4VoIsnjWIkBvBNitFECMWWwkUn9GsL9cP/K9SJdVSEJScQ=
  - secure: ZHDb/xvCA/xymtsy+XY/e7fyDgn87jZi7c8q1/CpTGqAE4BpKdT5GwUFFqjDo+x/r0WXhjxcVGMf2FgSLZaQpVCqM9hku7HCIJgwLvQI8E/sXvWJsEwVeQKHQ2WBK2sruKVx8KrpHqIeWJHNaFP0WO9JTBNZRGYdhOVuWfnt//I=
  - secure: N6VLh5hsdpsyB1LViznGcmjmxqvvdKAeRWekRt9JKlRktBWlEOMuz9khd9EFmJN/q5ijkhJocU0FNdLj+7DvXn48iM5EyM11UXK3VSWov/jr0EUZzAYBE/o98V9L3pD9/eQGDoPLTgkIIBJNQq3v91GMKANjSVlECrTdRDWfyAc=
