repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://stocksoftware.artifactoryonline.com/stocksoftware/public
   - https://stocksoftware.artifactoryonline.com/stocksoftware/oss
   - https://stocksoftware.artifactoryonline.com/stocksoftware/staging

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.14

  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.1
  javax_javaee: javax:javaee-api:jar:7.0

  gwt_user: org.realityforge.com.google.gwt:gwt-user:jar:2.8.2-v20191108
  gwt_dev: org.realityforge.com.google.gwt:gwt-dev:jar:2.8.2-v20191108

  #
  # GIN and associated dependencies
  gwt_gin: com.google.gwt.inject:gin:jar:2.1.2
  google_guice: com.google.inject:guice:jar:3.0
  google_guice_assistedinject: com.google.inject.extensions:guice-assistedinject:jar:3.0
  aopalliance: aopalliance:aopalliance:jar:1.0 # Required for guice
  javax_inject: javax.inject:javax.inject:jar:1

  # Test deps
  jndikit: org.realityforge.jndikit:jndikit:jar:1.4

  glassfish_embedded: fish.payara.extras:payara-embedded-all:jar:4.1.1.164

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.102

  testng: org.testng:testng:jar:6.11

  #
  # Mocking library
  mockito: org.mockito:mockito-all:jar:1.10.19

  keycloak_core: org.keycloak:keycloak-core:jar:2.0.0.Final
  keycloak_common: org.keycloak:keycloak-common:jar:2.0.0.Final
  keycloak_adapter_core: org.keycloak:keycloak-adapter-core:jar:2.0.0.Final
  keycloak_adapter_spi: org.keycloak:keycloak-adapter-spi:jar:2.0.0.Final

  simple_keycloak_service: org.realityforge.keycloak.sks:simple-keycloak-service:jar:0.1

  graphql_java: com.graphql-java:graphql-java:jar:13.0

  gwt_webpoller: org.realityforge.gwt.webpoller:gwt-webpoller:jar:0.9.1
