repositories:
  remote:
   - http://repo1.maven.org/maven2
   - https://stocksoftware.artifactoryonline.com/stocksoftware/public
   - https://stocksoftware.artifactoryonline.com/stocksoftware/oss

artifacts:
  idea_codestyle: au.com.stocksoftware.idea.codestyle:idea-codestyle:xml:1.13

  javax_jsr305: org.realityforge.javax.annotation:javax.annotation:jar:1.0.0
  javax_javaee: javax:javaee-api:jar:7.0

  gwt_user: com.google.gwt:gwt-user:jar:2.8.2
  gwt_dev: com.google.gwt:gwt-dev:jar:2.8.2

  #
  # GIN and associated dependencies
  gwt_gin: com.google.gwt.inject:gin:jar:2.1.2
  google_guice: com.google.inject:guice:jar:3.0
  google_guice_assistedinject: com.google.inject.extensions:guice-assistedinject:jar:3.0
  aopalliance: aopalliance:aopalliance:jar:1.0 # Required for guice
  javax_inject: javax.inject:javax.inject:jar:1

  # Test deps
  jndikit: org.realityforge.jndikit:jndikit:jar:1.4

  glassfish_embedded: fish.payara.extras:payara-embedded-all:jar:4.1.1.164

  guiceyloops: org.realityforge.guiceyloops:guiceyloops:jar:0.67

  testng: org.testng:testng:jar:6.11

  #
  # Mocking library
  mockito: org.mockito:mockito-all:jar:1.10.19

  keycloak_core: org.keycloak:keycloak-core:jar:2.0.0.Final
  keycloak_common: org.keycloak:keycloak-common:jar:2.0.0.Final
  keycloak_adapter_core: org.keycloak:keycloak-adapter-core:jar:2.0.0.Final
  keycloak_adapter_spi: org.keycloak:keycloak-adapter-spi:jar:2.0.0.Final

  simple_keycloak_service: org.realityforge.keycloak.sks:simple-keycloak-service:jar:0.1

  gwt_webpoller: org.realityforge.gwt.webpoller:gwt-webpoller:jar:0.9.1

  objenesis: org.objenesis:objenesis:jar:2.5.1

  powermock_core: org.powermock:powermock-core:jar:1.6.6
  powermock_reflect: org.powermock:powermock-reflect:jar:1.6.6
  powermock_testng_common: org.powermock:powermock-module-testng-common:jar:1.6.6
  powermock_testng: org.powermock:powermock-module-testng:jar:1.6.6
  powermock_testng_agent: org.powermock:powermock-module-testng-agent:jar:1.6.6
  powermock_api_mockito: org.powermock:powermock-api-mockito:jar:1.6.6
  powermock_api_mockito_common: org.powermock:powermock-api-mockito-common:jar:1.6.6
  powermock_api_support: org.powermock:powermock-api-support:jar:1.6.6
  javassist: org.javassist:javassist:jar:3.21.0-GA
  powermock_module_javaagent: org.powermock:powermock-module-javaagent:jar:1.6.6
